### PR TITLE
Bookdown conversion

### PR DESCRIPTION
**Pull request by gsrohde**
Added need files, deleted unneeded ones, and fixed some things in markdown files (mostly links) to work with bookdown.

@robkooper This needs a .travis.yml file.

@dlebauer The image in the SQL queries chapter is out of date in spite of the assertion in paragraph two that "the tables below are stable."  The second and third links on the "PEcAn R Package" page are broken, and I didn't know exactly what they should be.

### CODE REVIEW

**Review by dlebauer — APPROVED** [review]

**Comment by dlebauer** [comment]
Looks great - thank you for doing such a thorough job of migrating the content and updating the links!

**Comment by robkooper** [comment]
@dlebauer to fast on teh merge button, this did not have the .travis.yml file yet.

**Comment by dlebauer** [comment]
Sorry ... I created #2 to address the Travis.yml

And #3 for a few additional updates

**Comment by gsrohde** [comment]
@dlebauer @robkooper This brings up the question: Is there a way to require more than one reviewer to sign off on a PR?

**Comment by robkooper** [comment]
Not sure you want this, since what if you only add 1 reviewer. I think the trick is next time to have {WIP} in the title. That will prevent it from being merged.

Also I'd suggest in the body next time add checkboxes so we can make sure that all boxes are checked before it gets merged.

**Pull request merged**
